# -*- coding: utf-8 -*-
"""chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqwsUZLB_-WHfJPhya1iNl_PRg0C8VNE
"""

from src.rag_pipeline import load_rag_pipeline, ask_character
from src.memory_faiss import SemanticMemory

qa_chain = load_rag_pipeline()
memory = SemanticMemory()

print("💬 Chat with Seraphina! Type 'quit' to exit.")

while True:
    user_input = input("You: ")
    if user_input.lower() == "quit":
        break

    memory.add_message("user", user_input)
    past_context = memory.retrieve_relevant(user_input, k=3)
    context_text = "\n".join(past_context)

    query_with_context = f"{context_text}\nUser: {user_input}\nCharacter:"
    response = ask_character(query_with_context, qa_chain)

    memory.add_message("character", response)
    print("Seraphina:", response)